version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: healthcare_postgres
    environment:
      POSTGRES_DB: rds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: healthcare_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rds
      DB_SSL_MODE: disable
      ENVIRONMENT: development
      SERVER_PORT: 8080
      JWT_SECRET: your-jwt-secret-key
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
